In [10]:
import tensorflow as tf
from tensorflow import feature_column
from tensorflow.keras import layers
#tf.enable_eager_execution()
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import numpy as np
import pickle

In [11]:
with open('encodedStates.pickle', 'rb') as handle:
    data = pickle.load(handle)

In [12]:
dataMA = data["MA"]

In [13]:
dataMA.head()

HHSIZE  HHVEHCNT  DRIVER_0  DRIVER_1  EDUC_1  EDUC_2  EDUC_3  EDUC_4  \
0  0.899427         1         0         1       0       0       0       1   
1  0.899427         1         0         1       0       0       0       1   
2  0.899427         1         0         1       0       0       0       1   
3  0.899427         1         0         1       0       0       0       1   
4  1.798855         1         0         1       0       0       1       0   

   EDUC_5  URBANSIZE_1  URBANSIZE_2  URBANSIZE_3  URBANSIZE_4  URBANSIZE_5  \
0       0            0            0            0            0            1   
1       0            0            0            0            0            1   
2       0            0            0            0            0            1   
3       0            0            0            0            0            1   
4       0            0            0            0            0            1   

   URBANSIZE_6  URBRUR_1  URBRUR_2  
0            0         1         0  
1            0         1         0  
2            0         1         0  
3            0         1         0  
4            0         1         0

In [14]:
def df_to_np(dataframe,shuffle=True,batch_size=32,target="HHVEHCNT"):
    dataframe = dataframe.copy()
    labels = dataframe.pop(target)
    return dataframe.values, labels.values

In [47]:
train_X_MA, train_y_MA = df_to_np(dataMA)
print(train_X.shape)
print(train_y.shape)

(3211, 16)
(3211,)


In [48]:
modelMA = tf.keras.Sequential([
  tf.keras.layers.Dense(128,activation="relu"),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(64,activation="relu"),
  tf.keras.layers.Dense(4,activation="softmax")
])

modelMA.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

modelMA.fit(x=train_X_MA, y = train_y_MA,epochs=5, batch_size = 100, validation_split=0.2, shuffle=True)

Train on 2568 samples, validate on 643 samples
Epoch 1/5
2568/2568 [==============================] - 1s 291us/sample - loss: 1.0854 - accuracy: 0.5397 - val_loss: 1.0941 - val_accuracy: 0.5894
Epoch 2/5
2568/2568 [==============================] - 0s 64us/sample - loss: 0.8769 - accuracy: 0.6495 - val_loss: 1.0607 - val_accuracy: 0.5677
Epoch 3/5
2568/2568 [==============================] - 0s 48us/sample - loss: 0.8081 - accuracy: 0.6959 - val_loss: 1.0570 - val_accuracy: 0.5723
Epoch 4/5
2568/2568 [==============================] - 0s 49us/sample - loss: 0.7737 - accuracy: 0.6982 - val_loss: 1.1070 - val_accuracy: 0.5645
Epoch 5/5
2568/2568 [==============================] - 0s 63us/sample - loss: 0.7542 - accuracy: 0.7017 - val_loss: 1.1251 - val_accuracy: 0.5334


In [63]:
weightsMA_1 = modelMA.layers[0].get_weights()
weightsMA_1

[array([[-0.01743785,  0.15146367, -0.09180181, ...,  0.00345619,
         -0.10551102, -0.00605135],
        [ 0.14774986, -0.19362767,  0.16640139, ...,  0.01846397,
          0.20246075,  0.1673474 ],
        [-0.24041627, -0.07670439, -0.06856323, ...,  0.03091147,
         -0.11509847,  0.07246365],
        ...,
        [-0.10101233,  0.08829248,  0.09260352, ...,  0.04846853,
          0.08490252,  0.11700392],
        [-0.1294384 , -0.11843885, -0.16611134, ...,  0.10726339,
          0.02807734, -0.23838581],
        [-0.19377016, -0.08327387,  0.01341933, ...,  0.02931656,
         -0.1288538 ,  0.02309678]], dtype=float32),
 array([ 0.03301049, -0.00846896, -0.00715381,  0.        ,  0.00381368,
        -0.00182741, -0.01658083, -0.01100198, -0.01906062, -0.01750291,
         0.00036091, -0.0066485 ,  0.        , -0.00749844, -0.00858179,
         0.01194169,  0.018863  ,  0.01329608,  0.0113377 ,  0.00820245,
         0.00918575, -0.01912832, -0.01051839,  0.01784003, -0.009

In [53]:
dataCA = data["CA"]
dataCA.head()

HHSIZE  HHVEHCNT  DRIVER_0  DRIVER_1  EDUC_1  EDUC_2  EDUC_3  EDUC_4  \
0  1.533065         2         0         1       0       0       0       0   
1  1.533065         2         0         1       0       0       0       0   
2  1.533065         2         0         1       1       0       0       0   
3  1.533065         2         0         1       1       0       0       0   
4  1.533065         2         0         1       1       0       0       0   

   EDUC_5  URBANSIZE_1  URBANSIZE_2  URBANSIZE_3  URBANSIZE_4  URBANSIZE_5  \
0       1            0            1            0            0            0   
1       1            0            1            0            0            0   
2       0            0            1            0            0            0   
3       0            0            1            0            0            0   
4       0            0            1            0            0            0   

   URBANSIZE_6  URBRUR_1  URBRUR_2  
0            0         1         0  
1            0         1         0  
2            0         1         0  
3            0         1         0  
4            0         1         0

In [54]:
train_X_CA, train_y_CA = df_to_np(dataCA)
print(train_X_CA.shape)
print(train_y_CA.shape)

(155992, 16)
(155992,)


In [73]:
modelCA_benchmark = tf.keras.Sequential([
  tf.keras.layers.Dense(128,activation="relu"), 
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(64,activation="relu"),
  tf.keras.layers.Dense(4,activation="softmax")
])

modelCA_benchmark.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

modelCA_benchmark.fit(x=train_X_CA, y = train_y_CA,epochs=5, batch_size = 1000, validation_split=0.2, shuffle=True)

Train on 124793 samples, validate on 31199 samples
Epoch 1/5
124793/124793 [==============================] - 2s 14us/sample - loss: 0.9515 - accuracy: 0.5599 - val_loss: 0.9242 - val_accuracy: 0.5827
Epoch 2/5
124793/124793 [==============================] - 1s 10us/sample - loss: 0.9123 - accuracy: 0.5866 - val_loss: 0.9260 - val_accuracy: 0.5801
Epoch 3/5
124793/124793 [==============================] - 1s 10us/sample - loss: 0.9101 - accuracy: 0.5869 - val_loss: 0.9253 - val_accuracy: 0.5887
Epoch 4/5
124793/124793 [==============================] - 1s 10us/sample - loss: 0.9078 - accuracy: 0.5885 - val_loss: 0.9275 - val_accuracy: 0.5794
Epoch 5/5
124793/124793 [==============================] - 1s 10us/sample - loss: 0.9054 - accuracy: 0.5913 - val_loss: 0.9270 - val_accuracy: 0.5788


In [74]:
modelCA_benchmark.layers[0].get_weights()[0]

array([[ 0.08800914,  0.0604397 ,  0.15293552, ..., -0.01185746,
         0.17021427, -0.04332333],
       [-0.20824927, -0.0432914 ,  0.13712479, ...,  0.02268448,
        -0.14053394,  0.22549394],
       [ 0.12272537,  0.11387481,  0.10559276, ..., -0.18930861,
        -0.02590599, -0.09913554],
       ...,
       [ 0.10410998,  0.17682415, -0.05371061, ..., -0.03704657,
        -0.1258989 ,  0.12777427],
       [-0.01188823,  0.06813283,  0.07198166, ..., -0.11298712,
        -0.04864229, -0.13337116],
       [-0.22033869, -0.17739964,  0.08009589, ...,  0.15416807,
         0.07262819,  0.17758518]], dtype=float32)

In [75]:
modelCA_frozenTransfer = tf.keras.Sequential([
  tf.keras.layers.Dense(128,activation="relu", weights = weightsMA_1, trainable = False), 
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(64,activation="relu"),
  tf.keras.layers.Dense(4,activation="softmax")
])

modelCA_frozenTransfer.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

modelCA_frozenTransfer.fit(x=train_X_CA, y = train_y_CA,epochs=5, batch_size = 1000, validation_split=0.2, shuffle=True)

Train on 124793 samples, validate on 31199 samples
Epoch 1/5
124793/124793 [==============================] - 2s 13us/sample - loss: 0.9568 - accuracy: 0.5603 - val_loss: 0.9291 - val_accuracy: 0.5756
Epoch 2/5
124793/124793 [==============================] - 1s 9us/sample - loss: 0.9157 - accuracy: 0.5836 - val_loss: 0.9295 - val_accuracy: 0.5872
Epoch 3/5
124793/124793 [==============================] - 1s 9us/sample - loss: 0.9118 - accuracy: 0.5868 - val_loss: 0.9365 - val_accuracy: 0.5794
Epoch 4/5
124793/124793 [==============================] - 1s 9us/sample - loss: 0.9105 - accuracy: 0.5884 - val_loss: 0.9301 - val_accuracy: 0.5775
Epoch 5/5
124793/124793 [==============================] - 1s 9us/sample - loss: 0.9090 - accuracy: 0.5902 - val_loss: 0.9293 - val_accuracy: 0.5779


In [76]:
modelCA_frozenTransfer.layers[0].get_weights()

[array([[-0.01743785,  0.15146367, -0.09180181, ...,  0.00345619,
         -0.10551102, -0.00605135],
        [ 0.14774986, -0.19362767,  0.16640139, ...,  0.01846397,
          0.20246075,  0.1673474 ],
        [-0.24041627, -0.07670439, -0.06856323, ...,  0.03091147,
         -0.11509847,  0.07246365],
        ...,
        [-0.10101233,  0.08829248,  0.09260352, ...,  0.04846853,
          0.08490252,  0.11700392],
        [-0.1294384 , -0.11843885, -0.16611134, ...,  0.10726339,
          0.02807734, -0.23838581],
        [-0.19377016, -0.08327387,  0.01341933, ...,  0.02931656,
         -0.1288538 ,  0.02309678]], dtype=float32),
 array([ 0.03301049, -0.00846896, -0.00715381,  0.        ,  0.00381368,
        -0.00182741, -0.01658083, -0.01100198, -0.01906062, -0.01750291,
         0.00036091, -0.0066485 ,  0.        , -0.00749844, -0.00858179,
         0.01194169,  0.018863  ,  0.01329608,  0.0113377 ,  0.00820245,
         0.00918575, -0.01912832, -0.01051839,  0.01784003, -0.009

In [77]:
modelCA_unfrozenTransfer = tf.keras.Sequential([
  tf.keras.layers.Dense(128,activation="relu", weights = weightsMA_1, trainable = True), 
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(64,activation="relu"),
  tf.keras.layers.Dense(4,activation="softmax")
])

modelCA_unfrozenTransfer.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

modelCA_unfrozenTransfer.fit(x=train_X_CA, y = train_y_CA,epochs=5, batch_size = 1000, validation_split=0.2, shuffle=True)

Train on 124793 samples, validate on 31199 samples
Epoch 1/5
124793/124793 [==============================] - 2s 17us/sample - loss: 0.9573 - accuracy: 0.5638 - val_loss: 0.9264 - val_accuracy: 0.5825
Epoch 2/5
124793/124793 [==============================] - 1s 11us/sample - loss: 0.9141 - accuracy: 0.5866 - val_loss: 0.9285 - val_accuracy: 0.5777
Epoch 3/5
124793/124793 [==============================] - 1s 11us/sample - loss: 0.9099 - accuracy: 0.5876 - val_loss: 0.9209 - val_accuracy: 0.5877
Epoch 4/5
124793/124793 [==============================] - 1s 10us/sample - loss: 0.9080 - accuracy: 0.5884 - val_loss: 0.9267 - val_accuracy: 0.5798
Epoch 5/5
124793/124793 [==============================] - 1s 12us/sample - loss: 0.9074 - accuracy: 0.5901 - val_loss: 0.9257 - val_accuracy: 0.5882


In [78]:
modelCA_unfrozenTransfer.layers[0].get_weights()

[array([[-0.014664  ,  0.11785861, -0.15513219, ..., -0.00676504,
         -0.1251385 ,  0.01579178],
        [ 0.15762892, -0.2997449 ,  0.17039885, ..., -0.02325984,
          0.23792791,  0.154293  ],
        [-0.19500624, -0.09667541, -0.03705984, ...,  0.01451831,
         -0.1241397 ,  0.07681436],
        ...,
        [-0.10534956,  0.05610569,  0.10968623, ...,  0.01054381,
          0.0457502 ,  0.10684872],
        [-0.100294  , -0.15241517, -0.1270254 , ...,  0.08682017,
          0.05101245, -0.24085735],
        [-0.29831374, -0.08595566,  0.04155878, ...,  0.00787597,
         -0.11096412,  0.02886299]], dtype=float32),
 array([ 0.05576064, -0.03816479,  0.01693246,  0.02359311, -0.00066257,
        -0.00416742, -0.03645224, -0.02732079, -0.03220745, -0.0438571 ,
        -0.01324651, -0.01150343,  0.        , -0.02364383, -0.01629846,
         0.02499631,  0.02052838, -0.00944357,  0.00102755,  0.00489909,
        -0.00896177, -0.0365325 ,  0.00460326,  0.01872969, -0.008