In [1]:
import tensorflow as tf
from tensorflow import feature_column
from tensorflow.keras import layers
#tf.enable_eager_execution()
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import numpy as np
import pickle

In [2]:
with open('encodedStates.pickle', 'rb') as handle:
    data = pickle.load(handle)

In [3]:
dataMA = data["MA"]

In [4]:
dataMA.head()

HHSIZE  HHVEHCNT  DRIVER_0  DRIVER_1  EDUC_1  EDUC_2  EDUC_3  EDUC_4  \
0  0.899427         1         0         1       0       0       0       1   
1  0.899427         1         0         1       0       0       0       1   
2  0.899427         1         0         1       0       0       0       1   
3  0.899427         1         0         1       0       0       0       1   
4  1.798855         1         0         1       0       0       1       0   

   EDUC_5  URBANSIZE_1  URBANSIZE_2  URBANSIZE_3  URBANSIZE_4  URBANSIZE_5  \
0       0            0            0            0            0            1   
1       0            0            0            0            0            1   
2       0            0            0            0            0            1   
3       0            0            0            0            0            1   
4       0            0            0            0            0            1   

   URBANSIZE_6  URBRUR_1  URBRUR_2  
0            0         1         0  
1            0         1         0  
2            0         1         0  
3            0         1         0  
4            0         1         0

In [5]:
def df_to_np(dataframe,shuffle=True,batch_size=32,target="HHVEHCNT"):
    dataframe = dataframe.copy()
    labels = dataframe.pop(target)
    return dataframe.values, labels.values

In [6]:
train_X_MA, train_y_MA = df_to_np(dataMA)
print(train_X.shape)
print(train_y.shape)

NameError: name 'train_X' is not defined

In [17]:
modelMA = tf.keras.Sequential([
  tf.keras.layers.Dense(128,activation="relu"),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(64,activation="relu"),
  tf.keras.layers.Dense(4,activation="softmax")
])

modelMA.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

modelMA.fit(x=train_X_MA, y = train_y_MA,epochs=5, batch_size = 100, validation_split=0.2, shuffle=True)

Train on 2568 samples, validate on 643 samples
Epoch 1/5
2568/2568 [==============================] - 1s 386us/sample - loss: 1.0884 - accuracy: 0.5276 - val_loss: 1.0827 - val_accuracy: 0.5334
Epoch 2/5
2568/2568 [==============================] - 0s 46us/sample - loss: 0.8827 - accuracy: 0.6488 - val_loss: 1.0259 - val_accuracy: 0.5956
Epoch 3/5
2568/2568 [==============================] - 0s 45us/sample - loss: 0.8026 - accuracy: 0.6994 - val_loss: 1.0131 - val_accuracy: 0.5941
Epoch 4/5
2568/2568 [==============================] - 0s 47us/sample - loss: 0.7676 - accuracy: 0.6963 - val_loss: 1.0886 - val_accuracy: 0.5723
Epoch 5/5
2568/2568 [==============================] - 0s 46us/sample - loss: 0.7491 - accuracy: 0.6955 - val_loss: 1.1207 - val_accuracy: 0.5754


In [18]:
weightsMA_0 = modelMA.layers[0].get_weights()
weightsMA_0

[array([[ 0.09433921,  0.08552001, -0.03757235, ...,  0.17129667,
          0.03284126,  0.17968664],
        [ 0.00313148,  0.03992483,  0.12608412, ...,  0.01377496,
          0.06328232, -0.14373073],
        [ 0.10520969, -0.10832182,  0.08575378, ..., -0.06956522,
         -0.0376166 ,  0.17335953],
        ...,
        [-0.09595936,  0.03563687,  0.11502886, ..., -0.14083865,
          0.03889039,  0.04302691],
        [ 0.07176542, -0.16873108, -0.1302721 , ..., -0.18778199,
          0.03311263, -0.13192686],
        [-0.20638433, -0.08180811,  0.12548278, ..., -0.02919368,
         -0.01461214, -0.01296339]], dtype=float32),
 array([-0.00753754,  0.0070127 ,  0.02250249, -0.00757921, -0.01285502,
        -0.01073427,  0.01954687,  0.01350116,  0.01941331,  0.00048144,
         0.01918793,  0.        , -0.00564363,  0.03385548,  0.03471511,
        -0.00145573,  0.01093077,  0.01181996,  0.0130202 ,  0.00949713,
        -0.00919257,  0.0046165 ,  0.01635824,  0.00117564, -0.006

In [9]:
dataCA = data["CA"]
dataCA.head()

HHSIZE  HHVEHCNT  DRIVER_0  DRIVER_1  EDUC_1  EDUC_2  EDUC_3  EDUC_4  \
0  1.533065         2         0         1       0       0       0       0   
1  1.533065         2         0         1       0       0       0       0   
2  1.533065         2         0         1       1       0       0       0   
3  1.533065         2         0         1       1       0       0       0   
4  1.533065         2         0         1       1       0       0       0   

   EDUC_5  URBANSIZE_1  URBANSIZE_2  URBANSIZE_3  URBANSIZE_4  URBANSIZE_5  \
0       1            0            1            0            0            0   
1       1            0            1            0            0            0   
2       0            0            1            0            0            0   
3       0            0            1            0            0            0   
4       0            0            1            0            0            0   

   URBANSIZE_6  URBRUR_1  URBRUR_2  
0            0         1         0  
1            0         1         0  
2            0         1         0  
3            0         1         0  
4            0         1         0

In [19]:
train_X_CA, train_y_CA = df_to_np(dataCA)
print(train_X_CA.shape)
print(train_y_CA.shape)

(155992, 16)
(155992,)


In [20]:
modelCA_benchmark = tf.keras.Sequential([
  tf.keras.layers.Dense(128,activation="relu"), 
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(64,activation="relu"),
  tf.keras.layers.Dense(4,activation="softmax")
])

modelCA_benchmark.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

modelCA_benchmark.fit(x=train_X_CA, y = train_y_CA,epochs=5, batch_size = 1000, validation_split=0.2, shuffle=True)

Train on 124793 samples, validate on 31199 samples
Epoch 1/5
124793/124793 [==============================] - 3s 26us/sample - loss: 0.9609 - accuracy: 0.5602 - val_loss: 0.9292 - val_accuracy: 0.5809
Epoch 2/5
124793/124793 [==============================] - 2s 14us/sample - loss: 0.9118 - accuracy: 0.5854 - val_loss: 0.9264 - val_accuracy: 0.5805
Epoch 3/5
124793/124793 [==============================] - 2s 13us/sample - loss: 0.9107 - accuracy: 0.5867 - val_loss: 0.9289 - val_accuracy: 0.5776
Epoch 4/5
124793/124793 [==============================] - 1s 12us/sample - loss: 0.9096 - accuracy: 0.5889 - val_loss: 0.9380 - val_accuracy: 0.5684
Epoch 5/5
124793/124793 [==============================] - 2s 14us/sample - loss: 0.9068 - accuracy: 0.5909 - val_loss: 0.9268 - val_accuracy: 0.5871


In [21]:
modelCA_benchmark.layers[0].get_weights()[0]

array([[ 0.10642939, -0.05683518, -0.01366784, ..., -0.04643035,
         0.03741837, -0.17249231],
       [-0.24054039,  0.01373343, -0.24907263, ..., -0.1823448 ,
        -0.13559876, -0.16246088],
       [ 0.10646435,  0.00345892,  0.12632295, ...,  0.10338854,
         0.13297673,  0.17224425],
       ...,
       [-0.03930989, -0.18258093,  0.0304897 , ..., -0.00868373,
        -0.10267913,  0.17081751],
       [ 0.09013441, -0.04432919,  0.16407707, ..., -0.17009301,
         0.00287837, -0.12425587],
       [-0.0241148 ,  0.05180383, -0.11953254, ...,  0.00742468,
         0.12014724, -0.06619374]], dtype=float32)

In [22]:
modelCA_frozenTransfer = tf.keras.Sequential([
  tf.keras.layers.Dense(128,activation="relu", weights = weightsMA_0, trainable = False), 
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(64,activation="relu"),
  tf.keras.layers.Dense(4,activation="softmax")
])

modelCA_frozenTransfer.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

modelCA_frozenTransfer.fit(x=train_X_CA, y = train_y_CA,epochs=5, batch_size = 1000, validation_split=0.2, shuffle=True)

Train on 124793 samples, validate on 31199 samples
Epoch 1/5
124793/124793 [==============================] - 2s 14us/sample - loss: 0.9542 - accuracy: 0.5608 - val_loss: 0.9322 - val_accuracy: 0.5794
Epoch 2/5
124793/124793 [==============================] - 1s 10us/sample - loss: 0.9157 - accuracy: 0.5850 - val_loss: 0.9374 - val_accuracy: 0.5658
Epoch 3/5
124793/124793 [==============================] - 1s 9us/sample - loss: 0.9130 - accuracy: 0.5866 - val_loss: 0.9304 - val_accuracy: 0.5836
Epoch 4/5
124793/124793 [==============================] - 1s 10us/sample - loss: 0.9112 - accuracy: 0.5888 - val_loss: 0.9252 - val_accuracy: 0.5865
Epoch 5/5
124793/124793 [==============================] - 1s 11us/sample - loss: 0.9097 - accuracy: 0.5891 - val_loss: 0.9273 - val_accuracy: 0.5854


In [23]:
modelCA_frozenTransfer.layers[0].get_weights()

[array([[ 0.09433921,  0.08552001, -0.03757235, ...,  0.17129667,
          0.03284126,  0.17968664],
        [ 0.00313148,  0.03992483,  0.12608412, ...,  0.01377496,
          0.06328232, -0.14373073],
        [ 0.10520969, -0.10832182,  0.08575378, ..., -0.06956522,
         -0.0376166 ,  0.17335953],
        ...,
        [-0.09595936,  0.03563687,  0.11502886, ..., -0.14083865,
          0.03889039,  0.04302691],
        [ 0.07176542, -0.16873108, -0.1302721 , ..., -0.18778199,
          0.03311263, -0.13192686],
        [-0.20638433, -0.08180811,  0.12548278, ..., -0.02919368,
         -0.01461214, -0.01296339]], dtype=float32),
 array([-0.00753754,  0.0070127 ,  0.02250249, -0.00757921, -0.01285502,
        -0.01073427,  0.01954687,  0.01350116,  0.01941331,  0.00048144,
         0.01918793,  0.        , -0.00564363,  0.03385548,  0.03471511,
        -0.00145573,  0.01093077,  0.01181996,  0.0130202 ,  0.00949713,
        -0.00919257,  0.0046165 ,  0.01635824,  0.00117564, -0.006

In [24]:
modelCA_unfrozenTransfer = tf.keras.Sequential([
  tf.keras.layers.Dense(128,activation="relu", weights = weightsMA_0, trainable = True), 
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(64,activation="relu"),
  tf.keras.layers.Dense(4,activation="softmax")
])

modelCA_unfrozenTransfer.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

modelCA_unfrozenTransfer.fit(x=train_X_CA, y = train_y_CA,epochs=5, batch_size = 1000, validation_split=0.2, shuffle=True)

Train on 124793 samples, validate on 31199 samples
Epoch 1/5
124793/124793 [==============================] - 3s 22us/sample - loss: 0.9484 - accuracy: 0.5628 - val_loss: 0.9305 - val_accuracy: 0.5774
Epoch 2/5
124793/124793 [==============================] - 1s 11us/sample - loss: 0.9140 - accuracy: 0.5851 - val_loss: 0.9309 - val_accuracy: 0.5759
Epoch 3/5
124793/124793 [==============================] - 1s 10us/sample - loss: 0.9099 - accuracy: 0.5880 - val_loss: 0.9303 - val_accuracy: 0.5766
Epoch 4/5
124793/124793 [==============================] - 1s 10us/sample - loss: 0.9078 - accuracy: 0.5889 - val_loss: 0.9242 - val_accuracy: 0.5782
Epoch 5/5
124793/124793 [==============================] - 1s 10us/sample - loss: 0.9063 - accuracy: 0.5901 - val_loss: 0.9303 - val_accuracy: 0.5718


In [25]:
modelCA_unfrozenTransfer.layers[0].get_weights()

[array([[ 9.50121507e-02,  1.08234435e-01, -2.28928812e-02, ...,
          1.57651603e-01,  3.73591781e-02,  1.90145686e-01],
        [-4.88574058e-03,  5.15270419e-02,  9.13502127e-02, ...,
         -3.05880458e-05,  6.93143979e-02, -1.38573751e-01],
        [ 9.03245881e-02, -1.47407636e-01,  9.73863825e-02, ...,
         -6.55720755e-02, -3.40857729e-02,  1.72486112e-01],
        ...,
        [-8.62385109e-02,  6.64089471e-02,  9.31394771e-02, ...,
         -1.22892886e-01,  3.69603336e-02,  4.75985110e-02],
        [ 5.12960106e-02, -1.83725372e-01, -1.32552683e-01, ...,
         -1.87330946e-01,  4.57208417e-02, -1.37012035e-01],
        [-1.52422830e-01, -1.43068388e-01,  1.28894165e-01, ...,
         -1.37441559e-02, -6.18551187e-02,  3.08667263e-03]], dtype=float32),
 array([-2.32762061e-02, -2.95924172e-02,  1.96967851e-02, -6.71401946e-03,
        -3.75856310e-02, -2.88084801e-02,  2.39935070e-02,  1.29770301e-02,
         3.93512771e-02, -1.59190001e-03,  1.74360145e-02,  2.