In [1]:
import tensorflow as tf
from tensorflow import feature_column
from tensorflow.keras import layers
#tf.enable_eager_execution()
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import numpy as np
import pickle

In [2]:
with open('encodedStates.pickle', 'rb') as handle:
    data = pickle.load(handle)

In [3]:
dataMA = data["MA"]

In [4]:
dataMA.head()

HHSIZE  HHVEHCNT  DRIVER_0  DRIVER_1  EDUC_1  EDUC_2  EDUC_3  EDUC_4  \
0  0.899427         1         0         1       0       0       0       1   
1  0.899427         1         0         1       0       0       0       1   
2  0.899427         1         0         1       0       0       0       1   
3  0.899427         1         0         1       0       0       0       1   
4  1.798855         1         0         1       0       0       1       0   

   EDUC_5  URBANSIZE_1  URBANSIZE_2  URBANSIZE_3  URBANSIZE_4  URBANSIZE_5  \
0       0            0            0            0            0            1   
1       0            0            0            0            0            1   
2       0            0            0            0            0            1   
3       0            0            0            0            0            1   
4       0            0            0            0            0            1   

   URBANSIZE_6  URBRUR_1  URBRUR_2  
0            0         1         0  
1            0         1         0  
2            0         1         0  
3            0         1         0  
4            0         1         0

In [5]:
def df_to_np(dataframe,shuffle=True,batch_size=32,target="HHVEHCNT"):
    dataframe = dataframe.copy()
    labels = dataframe.pop(target)
    return dataframe.values, labels.values

In [6]:
train_X_MA, train_y_MA = df_to_np(dataMA)
print(train_X.shape)
print(train_y.shape)

NameError: name 'train_X' is not defined

In [7]:
modelMA = tf.keras.Sequential([
  tf.keras.layers.Dense(128,activation="relu"),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(64,activation="relu"),
  tf.keras.layers.Dense(4,activation="softmax")
])

modelMA.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

modelMA.fit(x=train_X_MA, y = train_y_MA,epochs=5, batch_size = 100, validation_split=0.2, shuffle=True)

Train on 2568 samples, validate on 643 samples
Epoch 1/5
2568/2568 [==============================] - 1s 355us/sample - loss: 1.0928 - accuracy: 0.5343 - val_loss: 1.0480 - val_accuracy: 0.5754
Epoch 2/5
2568/2568 [==============================] - 0s 46us/sample - loss: 0.8708 - accuracy: 0.6674 - val_loss: 1.0372 - val_accuracy: 0.5801
Epoch 3/5
2568/2568 [==============================] - 0s 48us/sample - loss: 0.8106 - accuracy: 0.6900 - val_loss: 1.1071 - val_accuracy: 0.5614
Epoch 4/5
2568/2568 [==============================] - 0s 42us/sample - loss: 0.7694 - accuracy: 0.6963 - val_loss: 1.0765 - val_accuracy: 0.5723
Epoch 5/5
2568/2568 [==============================] - 0s 46us/sample - loss: 0.7486 - accuracy: 0.6990 - val_loss: 1.1124 - val_accuracy: 0.5381


In [8]:
weightsMA_0 = modelMA.layers[0].get_weights()
weightsMA_0

[array([[ 0.16146778, -0.2114275 ,  0.00806019, ..., -0.15091166,
         -0.15316764, -0.16355145],
        [-0.00510243, -0.15372837, -0.06438292, ..., -0.03659481,
          0.17001641,  0.10256773],
        [-0.08721658,  0.01630916,  0.12446278, ..., -0.17490639,
         -0.10091607, -0.18295771],
        ...,
        [ 0.20816132,  0.09885196, -0.16056952, ...,  0.10421827,
          0.01446052, -0.04255879],
        [-0.16180807, -0.0584738 , -0.06912175, ..., -0.14443491,
          0.05999483, -0.15461421],
        [ 0.14206946, -0.05026925, -0.09361045, ..., -0.11257225,
         -0.18448469,  0.18336111]], dtype=float32),
 array([ 0.01807267, -0.02646597,  0.00136518, -0.01416819,  0.00831796,
         0.00454813, -0.008067  ,  0.0024819 ,  0.00499014, -0.00888215,
         0.03091212, -0.00508517, -0.00556349, -0.00707934,  0.04368664,
         0.01223597,  0.00298602,  0.01152899,  0.02477178,  0.01103156,
        -0.01276777, -0.00097959, -0.00303773, -0.00823832, -0.009

In [9]:
dataCA = data["CA"]
dataCA.head()

HHSIZE  HHVEHCNT  DRIVER_0  DRIVER_1  EDUC_1  EDUC_2  EDUC_3  EDUC_4  \
0  1.533065         2         0         1       0       0       0       0   
1  1.533065         2         0         1       0       0       0       0   
2  1.533065         2         0         1       1       0       0       0   
3  1.533065         2         0         1       1       0       0       0   
4  1.533065         2         0         1       1       0       0       0   

   EDUC_5  URBANSIZE_1  URBANSIZE_2  URBANSIZE_3  URBANSIZE_4  URBANSIZE_5  \
0       1            0            1            0            0            0   
1       1            0            1            0            0            0   
2       0            0            1            0            0            0   
3       0            0            1            0            0            0   
4       0            0            1            0            0            0   

   URBANSIZE_6  URBRUR_1  URBRUR_2  
0            0         1         0  
1            0         1         0  
2            0         1         0  
3            0         1         0  
4            0         1         0

In [10]:
train_X_CA, train_y_CA = df_to_np(dataCA)
print(train_X_CA.shape)
print(train_y_CA.shape)

(155992, 16)
(155992,)


In [11]:
modelCA_benchmark = tf.keras.Sequential([
  tf.keras.layers.Dense(128,activation="relu"), 
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(64,activation="relu"),
  tf.keras.layers.Dense(4,activation="softmax")
])

modelCA_benchmark.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

modelCA_benchmark.fit(x=train_X_CA, y = train_y_CA,epochs=5, batch_size = 1000, validation_split=0.2, shuffle=True)

Train on 124793 samples, validate on 31199 samples
Epoch 1/5
124793/124793 [==============================] - 2s 15us/sample - loss: 0.9553 - accuracy: 0.5599 - val_loss: 0.9261 - val_accuracy: 0.5769
Epoch 2/5
124793/124793 [==============================] - 1s 10us/sample - loss: 0.9136 - accuracy: 0.5862 - val_loss: 0.9294 - val_accuracy: 0.5723
Epoch 3/5
124793/124793 [==============================] - 2s 16us/sample - loss: 0.9097 - accuracy: 0.5869 - val_loss: 0.9233 - val_accuracy: 0.5872
Epoch 4/5
124793/124793 [==============================] - 2s 14us/sample - loss: 0.9073 - accuracy: 0.5888 - val_loss: 0.9234 - val_accuracy: 0.5831
Epoch 5/5
124793/124793 [==============================] - 2s 17us/sample - loss: 0.9072 - accuracy: 0.5904 - val_loss: 0.9228 - val_accuracy: 0.5780


In [12]:
modelCA_benchmark.layers[0].get_weights()[0]

array([[-0.19053136,  0.02595739, -0.21050896, ..., -0.07676836,
         0.14700328,  0.02427791],
       [ 0.08770394,  0.14293781,  0.16660129, ...,  0.15244879,
         0.05649608, -0.02446462],
       [ 0.16319767, -0.21831238, -0.07462218, ..., -0.16689365,
        -0.10558878,  0.08542293],
       ...,
       [ 0.09918969, -0.18402451, -0.02542645, ...,  0.07253549,
         0.15515429,  0.02777442],
       [ 0.1231924 , -0.12024619,  0.15361284, ...,  0.00880667,
        -0.11296156, -0.1528654 ],
       [-0.05517871, -0.1045403 , -0.11482907, ..., -0.11053555,
         0.01536542, -0.01073859]], dtype=float32)

In [23]:
modelCA_frozenTransfer = tf.keras.Sequential([
  tf.keras.layers.Dense(128,activation="relu", weights = weightsMA_0, trainable = False), 
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(64,activation="relu"),
  tf.keras.layers.Dense(4,activation="softmax")
])

modelCA_frozenTransfer.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

modelCA_frozenTransfer.fit(x=train_X_CA, y = train_y_CA,epochs=5, batch_size = 1000, validation_split=0.2, shuffle=True)

Train on 124793 samples, validate on 31199 samples
Epoch 1/5
124793/124793 [==============================] - 2s 13us/sample - loss: 0.9618 - accuracy: 0.5574 - val_loss: 0.9370 - val_accuracy: 0.5691
Epoch 2/5
124793/124793 [==============================] - 1s 9us/sample - loss: 0.9162 - accuracy: 0.5835 - val_loss: 0.9276 - val_accuracy: 0.5888
Epoch 3/5
124793/124793 [==============================] - 1s 9us/sample - loss: 0.9133 - accuracy: 0.5861 - val_loss: 0.9314 - val_accuracy: 0.5663
Epoch 4/5
124793/124793 [==============================] - 1s 9us/sample - loss: 0.9103 - accuracy: 0.5875 - val_loss: 0.9280 - val_accuracy: 0.5872
Epoch 5/5
124793/124793 [==============================] - 1s 10us/sample - loss: 0.9086 - accuracy: 0.5909 - val_loss: 0.9262 - val_accuracy: 0.5909


In [24]:
modelCA_frozenTransfer.layers[0].get_weights()

[array([[ 0.16146778, -0.2114275 ,  0.00806019, ..., -0.15091166,
         -0.15316764, -0.16355145],
        [-0.00510243, -0.15372837, -0.06438292, ..., -0.03659481,
          0.17001641,  0.10256773],
        [-0.08721658,  0.01630916,  0.12446278, ..., -0.17490639,
         -0.10091607, -0.18295771],
        ...,
        [ 0.20816132,  0.09885196, -0.16056952, ...,  0.10421827,
          0.01446052, -0.04255879],
        [-0.16180807, -0.0584738 , -0.06912175, ..., -0.14443491,
          0.05999483, -0.15461421],
        [ 0.14206946, -0.05026925, -0.09361045, ..., -0.11257225,
         -0.18448469,  0.18336111]], dtype=float32),
 array([ 0.01807267, -0.02646597,  0.00136518, -0.01416819,  0.00831796,
         0.00454813, -0.008067  ,  0.0024819 ,  0.00499014, -0.00888215,
         0.03091212, -0.00508517, -0.00556349, -0.00707934,  0.04368664,
         0.01223597,  0.00298602,  0.01152899,  0.02477178,  0.01103156,
        -0.01276777, -0.00097959, -0.00303773, -0.00823832, -0.009

In [25]:
modelCA_unfrozenTransfer = tf.keras.Sequential([
  tf.keras.layers.Dense(128,activation="relu", weights = weightsMA_0, trainable = True), 
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(128),
  #tf.keras.layers.Dropout(0.5),
  tf.keras.layers.Dense(64,activation="relu"),
  tf.keras.layers.Dense(4,activation="softmax")
])

modelCA_unfrozenTransfer.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

modelCA_unfrozenTransfer.fit(x=train_X_CA, y = train_y_CA,epochs=5, batch_size = 1000, validation_split=0.2, shuffle=True)

Train on 124793 samples, validate on 31199 samples
Epoch 1/5
124793/124793 [==============================] - 2s 18us/sample - loss: 0.9441 - accuracy: 0.5670 - val_loss: 0.9243 - val_accuracy: 0.5900
Epoch 2/5
124793/124793 [==============================] - 1s 11us/sample - loss: 0.9122 - accuracy: 0.5870 - val_loss: 0.9255 - val_accuracy: 0.5863
Epoch 3/5
124793/124793 [==============================] - 1s 11us/sample - loss: 0.9090 - accuracy: 0.5882 - val_loss: 0.9272 - val_accuracy: 0.5826
Epoch 4/5
124793/124793 [==============================] - 2s 12us/sample - loss: 0.9075 - accuracy: 0.5892 - val_loss: 0.9285 - val_accuracy: 0.5837
Epoch 5/5
124793/124793 [==============================] - 2s 15us/sample - loss: 0.9071 - accuracy: 0.5898 - val_loss: 0.9232 - val_accuracy: 0.5882


In [26]:
modelCA_unfrozenTransfer.layers[0].get_weights()

[array([[ 0.15892963, -0.21600224, -0.00449288, ..., -0.15091166,
         -0.19079284, -0.12145928],
        [-0.04705903, -0.15372837, -0.01670328, ..., -0.03659481,
          0.18272349,  0.18232025],
        [-0.08714383,  0.01177121,  0.1213928 , ..., -0.17490639,
         -0.0798448 , -0.24709666],
        ...,
        [ 0.20535643,  0.09431405, -0.17895766, ...,  0.10421827,
          0.00610478, -0.01775966],
        [-0.15536349, -0.0584738 , -0.06722983, ..., -0.14443491,
          0.08167219, -0.25717324],
        [ 0.11471581, -0.05480718, -0.10901158, ..., -0.11257225,
         -0.19919479,  0.21930262]], dtype=float32),
 array([ 1.09600984e-02, -3.10039166e-02,  2.00786442e-03, -2.80904006e-02,
        -4.99837985e-03,  2.26009381e-03, -3.42654698e-02, -1.26695484e-02,
        -1.09452941e-02, -6.21617725e-03,  4.10633124e-02, -2.23838966e-02,
        -3.48143354e-02, -3.36430743e-02,  4.27854843e-02,  1.62839275e-02,
        -2.48672757e-02,  2.22368203e-02,  2.68282592e